//HintName: RefFieldAttribute.g.cs
#pragma warning disable
// <auto-generated/>
using global::System;
namespace PrimaryParameter.SG
{
    [AttributeUsage(AttributeTargets.Parameter, Inherited = false, AllowMultiple = true)]
    sealed class RefFieldAttribute : Attribute
    {
        public string Name { get; init; }
        public string Scope { get; init; }
        public bool IsReadonlyRef { get; init; }
        public bool IsRefReadonly { get; init; }
        public string Summary { get; init; }
    }
}
