//HintName: FaustVX.PrimaryParameter.SG.g.cs
#pragma warning disable
// <auto-generated/>
partial class C
{
    /// <summary>
    /// Documentation
    /// New Line
    /// </summary>
    public int I { get; init; } = i;
}
