name: Update NuGet

on:
  push:
    tags:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest

    name: Update NuGet 
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'
      - name: Pack Release
        run: dotnet pack ./PrimaryParameter.SG/
      - name: Push Package to NuGet.org
        run: dotnet nuget push **/*.nupkg --api-key ${{ secrets.NUGET_ORG_API_KEY }} --source https://api.nuget.org/v3/index.json
